/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-04-14 at 05:57:24 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.publisher.model;

/**
 * Model definition for EmailPayload.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Publisher &amp; Content Engine. For a
 * detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class EmailPayload
        extends com.google.api.client.json.GenericJson
{

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private EmailPayloadContent content;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private EmailFrom from;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private EmailRecipients recipients;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private EmailReplyTo replyTo;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String subject;

    /**
     * @return value or {@code null} for none
     */
    public EmailPayloadContent getContent()
    {
        return content;
    }

    /**
     * @param content content or {@code null} for none
     */
    public EmailPayload setContent( EmailPayloadContent content )
    {
        this.content = content;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public EmailFrom getFrom()
    {
        return from;
    }

    /**
     * @param from from or {@code null} for none
     */
    public EmailPayload setFrom( EmailFrom from )
    {
        this.from = from;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public EmailRecipients getRecipients()
    {
        return recipients;
    }

    /**
     * @param recipients recipients or {@code null} for none
     */
    public EmailPayload setRecipients( EmailRecipients recipients )
    {
        this.recipients = recipients;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public EmailReplyTo getReplyTo()
    {
        return replyTo;
    }

    /**
     * @param replyTo replyTo or {@code null} for none
     */
    public EmailPayload setReplyTo( EmailReplyTo replyTo )
    {
        this.replyTo = replyTo;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getSubject()
    {
        return subject;
    }

    /**
     * @param subject subject or {@code null} for none
     */
    public EmailPayload setSubject( java.lang.String subject )
    {
        this.subject = subject;
        return this;
    }

    @Override
    public EmailPayload set( String fieldName, Object value )
    {
        return ( EmailPayload ) super.set( fieldName, value );
    }

    @Override
    public EmailPayload clone()
    {
        return ( EmailPayload ) super.clone();
    }

}
